package main

import "github.com/LeonArif/Abtekindo/backend/internal/store"

// seedProducts is the starting catalog.
//
// TODO(abtekindo): Model names, specifications and prices below are realistic
// placeholders for the Indonesian market, not a confirmed price list. Confirm
// every row against current supplier pricing before launch, then maintain the
// catalog through the admin CMS rather than by editing this file.
//
// The seeder only inserts slugs that do not exist yet, so re-running it never
// overwrites an edit made in the CMS.
var seedProducts = []store.CreateProductParams{
	// ---------------------------------------------------------------- Daikin
	{
		Slug:          "daikin-standard-ftv15cxv-05pk",
		Name:          "Daikin Standard FTV15CXV 0,5 PK",
		Brand:         store.BrandDaikin,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    0.5,
		Btu:           5000,
		StartingPrice: 3_150_000,
		Inverter:      false,
		Refrigerant:   "R32",
		PowerWatt:     380,
		RoomSize:      "8 - 12 m²",
		Description:   "AC split Daikin seri Standard untuk kamar tidur berukuran kecil. Perawatan mudah dan suku cadang mudah didapat.",
		Features:      []string{"Refrigeran R32 ramah lingkungan", "Mode Powerful", "Timer 24 jam", "Auto restart", "Filter anti-bakteri"},
		SortOrder:     10,
	},
	{
		Slug:          "daikin-standard-ftv25cxv-1pk",
		Name:          "Daikin Standard FTV25CXV 1 PK",
		Brand:         store.BrandDaikin,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    1,
		Btu:           9000,
		StartingPrice: 4_250_000,
		Inverter:      false,
		Refrigerant:   "R32",
		PowerWatt:     660,
		RoomSize:      "14 - 18 m²",
		Description:   "Pilihan paling umum untuk kamar tidur utama dan ruang kerja. Pendinginan cepat dengan biaya perawatan rendah.",
		Features:      []string{"Refrigeran R32 ramah lingkungan", "Mode Powerful", "Timer 24 jam", "Auto restart", "Coil anti-korosi"},
		SortOrder:     11,
	},
	{
		Slug:          "daikin-smile-inverter-ftkc25uvm-1pk",
		Name:          "Daikin Smile Inverter FTKC25UVM 1 PK",
		Brand:         store.BrandDaikin,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    1,
		Btu:           9000,
		StartingPrice: 6_150_000,
		Inverter:      true,
		Refrigerant:   "R32",
		PowerWatt:     590,
		RoomSize:      "14 - 18 m²",
		Description:   "Seri inverter terlaris Daikin. Konsumsi listrik jauh lebih hemat untuk pemakaian harian di atas 8 jam.",
		Features:      []string{"Kompresor inverter hemat listrik", "Refrigeran R32", "Mode Econo", "Mode tidur", "Filter penangkap debu", "Operasi senyap"},
		Featured:      true,
		SortOrder:     1,
	},
	{
		Slug:          "daikin-smile-inverter-ftkc35uvm-15pk",
		Name:          "Daikin Smile Inverter FTKC35UVM 1,5 PK",
		Brand:         store.BrandDaikin,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    1.5,
		Btu:           12000,
		StartingPrice: 7_850_000,
		Inverter:      true,
		Refrigerant:   "R32",
		PowerWatt:     900,
		RoomSize:      "18 - 24 m²",
		Description:   "Kapasitas 1,5 PK untuk ruang keluarga atau kamar berukuran besar, dengan efisiensi inverter.",
		Features:      []string{"Kompresor inverter hemat listrik", "Refrigeran R32", "Mode Econo", "Mode tidur", "Auto restart", "Operasi senyap"},
		Featured:      true,
		SortOrder:     2,
	},
	{
		Slug:          "daikin-cassette-fcf50cvm-2pk",
		Name:          "Daikin Cassette FCF50CVM 2 PK",
		Brand:         store.BrandDaikin,
		Type:          store.ProductTypeCassette,
		CapacityPk:    2,
		Btu:           18000,
		StartingPrice: 14_500_000,
		Inverter:      false,
		Refrigerant:   "R32",
		PowerWatt:     1720,
		RoomSize:      "24 - 32 m²",
		Description:   "AC cassette tanam plafon untuk kantor, ruang meeting, dan area komersial. Distribusi udara 4 arah.",
		Features:      []string{"Distribusi udara 4 arah", "Refrigeran R32", "Pompa pembuangan air bawaan", "Remote kabel", "Perawatan dari sisi bawah"},
		SortOrder:     12,
	},

	// ------------------------------------------------------------------ Gree
	{
		Slug:          "gree-fairy-gwc05c3-05pk",
		Name:          "Gree Fairy GWC-05C3 0,5 PK",
		Brand:         store.BrandGree,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    0.5,
		Btu:           5000,
		StartingPrice: 2_850_000,
		Inverter:      false,
		Refrigerant:   "R32",
		PowerWatt:     400,
		RoomSize:      "8 - 12 m²",
		Description:   "Pilihan ekonomis untuk kamar kos, kamar anak, atau ruang kecil lainnya.",
		Features:      []string{"Refrigeran R32", "Mode Turbo", "Timer 24 jam", "Auto restart", "Mode tidur"},
		SortOrder:     20,
	},
	{
		Slug:          "gree-lomo-gwc09c3-1pk",
		Name:          "Gree Lomo GWC-09C3 1 PK",
		Brand:         store.BrandGree,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    1,
		Btu:           9000,
		StartingPrice: 3_750_000,
		Inverter:      false,
		Refrigerant:   "R32",
		PowerWatt:     700,
		RoomSize:      "14 - 18 m²",
		Description:   "AC 1 PK dengan harga bersaing. Cocok untuk kebutuhan rumah tangga sehari-hari.",
		Features:      []string{"Refrigeran R32", "Mode Turbo", "Filter anti-bakteri", "Timer 24 jam", "Auto restart"},
		Featured:      true,
		SortOrder:     3,
	},
	{
		Slug:          "gree-fairy-inverter-gwc09d3-1pk",
		Name:          "Gree Fairy Inverter GWC-09D3 1 PK",
		Brand:         store.BrandGree,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    1,
		Btu:           9000,
		StartingPrice: 5_250_000,
		Inverter:      true,
		Refrigerant:   "R32",
		PowerWatt:     610,
		RoomSize:      "14 - 18 m²",
		Description:   "Versi inverter dari seri Fairy. Titik masuk paling terjangkau untuk AC inverter.",
		Features:      []string{"Kompresor inverter hemat listrik", "Refrigeran R32", "Mode Turbo", "Mode tidur", "Self-cleaning"},
		SortOrder:     21,
	},
	{
		Slug:          "gree-lomo-gwc12c3-15pk",
		Name:          "Gree Lomo GWC-12C3 1,5 PK",
		Brand:         store.BrandGree,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    1.5,
		Btu:           12000,
		StartingPrice: 5_150_000,
		Inverter:      false,
		Refrigerant:   "R32",
		PowerWatt:     1080,
		RoomSize:      "18 - 24 m²",
		Description:   "Kapasitas 1,5 PK untuk ruang tamu atau ruang keluarga berukuran sedang.",
		Features:      []string{"Refrigeran R32", "Mode Turbo", "Timer 24 jam", "Auto restart", "Coil anti-korosi"},
		SortOrder:     22,
	},
	{
		Slug:          "gree-floor-standing-gvc27ah-3pk",
		Name:          "Gree Floor Standing GVC-27AH 3 PK",
		Brand:         store.BrandGree,
		Type:          store.ProductTypeFloorStanding,
		CapacityPk:    3,
		Btu:           27000,
		StartingPrice: 19_500_000,
		Inverter:      false,
		Refrigerant:   "R410A",
		PowerWatt:     2550,
		RoomSize:      "40 - 55 m²",
		Description:   "AC berdiri untuk aula, restoran, ruang pamer, dan ruangan bervolume besar.",
		Features:      []string{"Hembusan udara jarak jauh", "Mode Turbo", "Panel kontrol digital", "Filter mudah dilepas", "Roda pemindah"},
		SortOrder:     23,
	},

	// ------------------------------------------------------------- Panasonic
	{
		Slug:          "panasonic-standard-cs-yn5wkj-05pk",
		Name:          "Panasonic Standard CS-YN5WKJ 0,5 PK",
		Brand:         store.BrandPanasonic,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    0.5,
		Btu:           5000,
		StartingPrice: 3_050_000,
		Inverter:      false,
		Refrigerant:   "R32",
		PowerWatt:     380,
		RoomSize:      "8 - 12 m²",
		Description:   "Seri standar Panasonic yang dikenal awet dan mudah diservis.",
		Features:      []string{"Refrigeran R32", "Mode Powerful", "Timer 24 jam", "Auto restart", "Filter mudah dibersihkan"},
		SortOrder:     30,
	},
	{
		Slug:          "panasonic-standard-cs-yn9wkj-1pk",
		Name:          "Panasonic Standard CS-YN9WKJ 1 PK",
		Brand:         store.BrandPanasonic,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    1,
		Btu:           9000,
		StartingPrice: 4_150_000,
		Inverter:      false,
		Refrigerant:   "R32",
		PowerWatt:     660,
		RoomSize:      "14 - 18 m²",
		Description:   "AC 1 PK non-inverter dari Panasonic, pilihan aman untuk pemakaian rumah tangga.",
		Features:      []string{"Refrigeran R32", "Mode Powerful", "Timer 24 jam", "Auto restart", "Coil anti-korosi"},
		SortOrder:     31,
	},
	{
		Slug:          "panasonic-premium-inverter-cs-pu9akj-1pk",
		Name:          "Panasonic Premium Inverter CS-PU9AKJ 1 PK",
		Brand:         store.BrandPanasonic,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    1,
		Btu:           9000,
		StartingPrice: 6_450_000,
		Inverter:      true,
		Refrigerant:   "R32",
		PowerWatt:     570,
		RoomSize:      "14 - 18 m²",
		Description:   "Inverter kelas premium dengan pendinginan cepat dan konsumsi daya rendah pada beban ringan.",
		Features:      []string{"Kompresor inverter hemat listrik", "Refrigeran R32", "Mode Powerful", "Mode tidur", "Filter PM2.5", "Operasi senyap"},
		Featured:      true,
		SortOrder:     4,
	},
	{
		Slug:          "panasonic-premium-inverter-cs-pu12akj-15pk",
		Name:          "Panasonic Premium Inverter CS-PU12AKJ 1,5 PK",
		Brand:         store.BrandPanasonic,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    1.5,
		Btu:           12000,
		StartingPrice: 8_150_000,
		Inverter:      true,
		Refrigerant:   "R32",
		PowerWatt:     880,
		RoomSize:      "18 - 24 m²",
		Description:   "Inverter 1,5 PK untuk ruang keluarga yang dipakai lama setiap hari.",
		Features:      []string{"Kompresor inverter hemat listrik", "Refrigeran R32", "Mode Powerful", "Mode tidur", "Filter PM2.5", "Auto restart"},
		SortOrder:     32,
	},
	{
		Slug:          "panasonic-nanoe-inverter-cs-xu18ukp-2pk",
		Name:          "Panasonic Nanoe-G Inverter CS-XU18UKP 2 PK",
		Brand:         store.BrandPanasonic,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    2,
		Btu:           18000,
		StartingPrice: 11_900_000,
		Inverter:      true,
		Refrigerant:   "R32",
		PowerWatt:     1450,
		RoomSize:      "24 - 32 m²",
		Description:   "Kapasitas 2 PK dengan teknologi pemurnian udara Nanoe-G untuk ruangan luas.",
		Features:      []string{"Kompresor inverter hemat listrik", "Teknologi Nanoe-G", "Refrigeran R32", "Mode Powerful", "Filter PM2.5", "Operasi senyap"},
		SortOrder:     33,
	},

	// ----------------------------------------------------------------- Midea
	{
		Slug:          "midea-all-easy-msafa05crn8-05pk",
		Name:          "Midea All Easy MSAFA-05CRN8 0,5 PK",
		Brand:         store.BrandMidea,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    0.5,
		Btu:           5000,
		StartingPrice: 2_750_000,
		Inverter:      false,
		Refrigerant:   "R32",
		PowerWatt:     370,
		RoomSize:      "8 - 12 m²",
		Description:   "Harga paling terjangkau di katalog kami untuk kamar berukuran kecil.",
		Features:      []string{"Refrigeran R32", "Mode Turbo", "Timer 24 jam", "Auto restart", "Self-cleaning"},
		SortOrder:     40,
	},
	{
		Slug:          "midea-xtreme-cool-msag09crn8-1pk",
		Name:          "Midea Xtreme Cool MSAG-09CRN8 1 PK",
		Brand:         store.BrandMidea,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    1,
		Btu:           9000,
		StartingPrice: 3_550_000,
		Inverter:      false,
		Refrigerant:   "R32",
		PowerWatt:     680,
		RoomSize:      "14 - 18 m²",
		Description:   "AC 1 PK dengan pendinginan cepat dan harga kompetitif.",
		Features:      []string{"Refrigeran R32", "Mode Turbo", "Timer 24 jam", "Auto restart", "Filter anti-bakteri"},
		Featured:      true,
		SortOrder:     5,
	},
	{
		Slug:          "midea-xtreme-save-inverter-msagbu12hrdn8-15pk",
		Name:          "Midea Xtreme Save Inverter MSAGBU-12HRDN8 1,5 PK",
		Brand:         store.BrandMidea,
		Type:          store.ProductTypeSplitWall,
		CapacityPk:    1.5,
		Btu:           12000,
		StartingPrice: 6_750_000,
		Inverter:      true,
		Refrigerant:   "R32",
		PowerWatt:     920,
		RoomSize:      "18 - 24 m²",
		Description:   "Inverter 1,5 PK dengan harga di bawah rata-rata kelasnya.",
		Features:      []string{"Kompresor inverter hemat listrik", "Refrigeran R32", "Mode Turbo", "Mode tidur", "Self-cleaning", "Coil anti-korosi"},
		Featured:      true,
		SortOrder:     6,
	},
	{
		Slug:          "midea-portable-mpf09crn1-1pk",
		Name:          "Midea Portable MPF-09CRN1 1 PK",
		Brand:         store.BrandMidea,
		Type:          store.ProductTypePortable,
		CapacityPk:    1,
		Btu:           9000,
		StartingPrice: 4_350_000,
		Inverter:      false,
		Refrigerant:   "R410A",
		PowerWatt:     1000,
		RoomSize:      "12 - 16 m²",
		Description:   "AC portable tanpa instalasi permanen. Cocok untuk ruangan sewa atau kebutuhan sementara.",
		Features:      []string{"Tanpa instalasi permanen", "Roda pemindah", "Mode dehumidifier", "Timer 24 jam", "Remote control"},
		SortOrder:     41,
	},
	{
		Slug:          "midea-ceiling-suspended-mub18crn1-2pk",
		Name:          "Midea Ceiling Suspended MUB-18CRN1 2 PK",
		Brand:         store.BrandMidea,
		Type:          store.ProductTypeCeilingSuspended,
		CapacityPk:    2,
		Btu:           18000,
		StartingPrice: 13_500_000,
		Inverter:      false,
		Refrigerant:   "R410A",
		PowerWatt:     1750,
		RoomSize:      "24 - 32 m²",
		Description:   "Unit gantung plafon untuk ruangan tanpa plafon gantung, seperti ruko dan bengkel.",
		Features:      []string{"Hembusan udara panjang", "Pemasangan gantung plafon", "Mode Turbo", "Remote kabel opsional", "Filter mudah dilepas"},
		SortOrder:     42,
	},
}
