// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT count(*) FROM admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (email, password_hash, name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, created_at, updated_at
`

type CreateAdminUserParams struct {
	Email        string
	PasswordHash string
	Name         string
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.Email, arg.PasswordHash, arg.Name)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (user_id, refresh_token_hash, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, refresh_token_hash, user_agent, ip, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	UserID           pgtype.UUID
	RefreshTokenHash []byte
	UserAgent        string
	Ip               *netip.Addr
	ExpiresAt        pgtype.Timestamptz
}

// --------------------------------------------------------------------------
// Sessions
// --------------------------------------------------------------------------
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < now() - interval '30 days'
`

// Housekeeping: rows that can no longer authenticate anything.
func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, user_id, refresh_token_hash, user_agent, ip, expires_at, revoked_at, created_at FROM sessions
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

// Both conditions matter: an expired session and a revoked session must be
// indistinguishable from a nonexistent one.
func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminUserByEmail = `-- name: GetAdminUserByEmail :one
SELECT id, email, password_hash, name, created_at, updated_at FROM admin_users WHERE email = $1
`

func (q *Queries) GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminUserByID = `-- name: GetAdminUserByID :one
SELECT id, email, password_hash, name, created_at, updated_at FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminUserByID(ctx context.Context, id pgtype.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions SET revoked_at = now()
WHERE refresh_token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, refreshTokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSessionByTokenHash, refreshTokenHash)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admin_users SET password_hash = $2 WHERE id = $1
`

type UpdateAdminPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.ID, arg.PasswordHash)
	return err
}
