// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leads.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLeadsByStatus = `-- name: CountLeadsByStatus :many
SELECT status, count(*) AS total FROM leads GROUP BY status
`

type CountLeadsByStatusRow struct {
	Status LeadStatus
	Total  int64
}

// Powers the unread badge in the admin navigation.
func (q *Queries) CountLeadsByStatus(ctx context.Context) ([]CountLeadsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countLeadsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountLeadsByStatusRow{}
	for rows.Next() {
		var i CountLeadsByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRecentLeadsByIP = `-- name: CountRecentLeadsByIP :one
SELECT count(*) FROM leads
WHERE ip = $1 AND created_at > now() - $2::interval
`

type CountRecentLeadsByIPParams struct {
	Ip     *netip.Addr
	Within pgtype.Interval
}

// Second layer of abuse control behind the in-memory rate limiter. The limiter
// resets when the process restarts; this does not.
func (q *Queries) CountRecentLeadsByIP(ctx context.Context, arg CountRecentLeadsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentLeadsByIP, arg.Ip, arg.Within)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (name, phone, email, message, source, product_id, service_id, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, phone, email, message, source, product_id, service_id, status, ip, user_agent, created_at, updated_at
`

type CreateLeadParams struct {
	Name      string
	Phone     string
	Email     string
	Message   string
	Source    LeadSource
	ProductID pgtype.UUID
	ServiceID pgtype.UUID
	Ip        *netip.Addr
	UserAgent string
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Message,
		arg.Source,
		arg.ProductID,
		arg.ServiceID,
		arg.Ip,
		arg.UserAgent,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Message,
		&i.Source,
		&i.ProductID,
		&i.ServiceID,
		&i.Status,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeadByID = `-- name: GetLeadByID :one
SELECT id, name, phone, email, message, source, product_id, service_id, status, ip, user_agent, created_at, updated_at FROM leads WHERE id = $1
`

func (q *Queries) GetLeadByID(ctx context.Context, id pgtype.UUID) (Lead, error) {
	row := q.db.QueryRow(ctx, getLeadByID, id)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Message,
		&i.Source,
		&i.ProductID,
		&i.ServiceID,
		&i.Status,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeads = `-- name: ListLeads :many
SELECT
    leads.id, leads.name, leads.phone, leads.email, leads.message, leads.source, leads.product_id, leads.service_id, leads.status, leads.ip, leads.user_agent, leads.created_at, leads.updated_at,
    count(*) OVER () AS total_count
FROM leads
WHERE ($1::lead_status IS NULL OR status = $1::lead_status)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListLeadsParams struct {
	Status       *LeadStatus
	ResultOffset int32
	ResultLimit  int32
}

type ListLeadsRow struct {
	Lead       Lead
	TotalCount int64
}

// Admin inbox. A null status filter returns every lead.
func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]ListLeadsRow, error) {
	rows, err := q.db.Query(ctx, listLeads, arg.Status, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeadsRow{}
	for rows.Next() {
		var i ListLeadsRow
		if err := rows.Scan(
			&i.Lead.ID,
			&i.Lead.Name,
			&i.Lead.Phone,
			&i.Lead.Email,
			&i.Lead.Message,
			&i.Lead.Source,
			&i.Lead.ProductID,
			&i.Lead.ServiceID,
			&i.Lead.Status,
			&i.Lead.Ip,
			&i.Lead.UserAgent,
			&i.Lead.CreatedAt,
			&i.Lead.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeadStatus = `-- name: UpdateLeadStatus :one
UPDATE leads SET status = $2 WHERE id = $1 RETURNING id, name, phone, email, message, source, product_id, service_id, status, ip, user_agent, created_at, updated_at
`

type UpdateLeadStatusParams struct {
	ID     pgtype.UUID
	Status LeadStatus
}

func (q *Queries) UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLeadStatus, arg.ID, arg.Status)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Message,
		&i.Source,
		&i.ProductID,
		&i.ServiceID,
		&i.Status,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
