// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Brand string

const (
	BrandGree      Brand = "gree"
	BrandDaikin    Brand = "daikin"
	BrandPanasonic Brand = "panasonic"
	BrandMidea     Brand = "midea"
)

func (e *Brand) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Brand(s)
	case string:
		*e = Brand(s)
	default:
		return fmt.Errorf("unsupported scan type for Brand: %T", src)
	}
	return nil
}

type NullBrand struct {
	Brand Brand
	Valid bool // Valid is true if Brand is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBrand) Scan(value interface{}) error {
	if value == nil {
		ns.Brand, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Brand.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBrand) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Brand), nil
}

type LeadSource string

const (
	LeadSourceContact LeadSource = "contact"
	LeadSourceService LeadSource = "service"
	LeadSourceProduct LeadSource = "product"
)

func (e *LeadSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeadSource(s)
	case string:
		*e = LeadSource(s)
	default:
		return fmt.Errorf("unsupported scan type for LeadSource: %T", src)
	}
	return nil
}

type NullLeadSource struct {
	LeadSource LeadSource
	Valid      bool // Valid is true if LeadSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeadSource) Scan(value interface{}) error {
	if value == nil {
		ns.LeadSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeadSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeadSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeadSource), nil
}

type LeadStatus string

const (
	LeadStatusNew       LeadStatus = "new"
	LeadStatusContacted LeadStatus = "contacted"
	LeadStatusClosed    LeadStatus = "closed"
)

func (e *LeadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeadStatus(s)
	case string:
		*e = LeadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LeadStatus: %T", src)
	}
	return nil
}

type NullLeadStatus struct {
	LeadStatus LeadStatus
	Valid      bool // Valid is true if LeadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LeadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeadStatus), nil
}

type ProductType string

const (
	ProductTypeSplitWall        ProductType = "split-wall"
	ProductTypeCassette         ProductType = "cassette"
	ProductTypeFloorStanding    ProductType = "floor-standing"
	ProductTypeCeilingSuspended ProductType = "ceiling-suspended"
	ProductTypePortable         ProductType = "portable"
)

func (e *ProductType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductType(s)
	case string:
		*e = ProductType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductType: %T", src)
	}
	return nil
}

type NullProductType struct {
	ProductType ProductType
	Valid       bool // Valid is true if ProductType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductType) Scan(value interface{}) error {
	if value == nil {
		ns.ProductType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductType), nil
}

type AdminUser struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Lead struct {
	ID        pgtype.UUID
	Name      string
	Phone     string
	Email     string
	Message   string
	Source    LeadSource
	ProductID pgtype.UUID
	ServiceID pgtype.UUID
	Status    LeadStatus
	Ip        *netip.Addr
	UserAgent string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Product struct {
	ID            pgtype.UUID
	Slug          string
	Name          string
	Brand         Brand
	Type          ProductType
	CapacityPk    float64
	Btu           int32
	StartingPrice int64
	Inverter      bool
	Refrigerant   string
	PowerWatt     int32
	RoomSize      string
	Description   string
	Features      []string
	Featured      bool
	Published     bool
	SortOrder     int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ProductImage struct {
	ID        pgtype.UUID
	ProductID pgtype.UUID
	ObjectKey string
	Alt       string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
}

type Service struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Summary     string
	Description string
	Bullets     []string
	Icon        string
	Published   bool
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ServiceRate struct {
	ID        pgtype.UUID
	ServiceID pgtype.UUID
	Label     string
	Unit      string
	PriceFrom int64
	Note      string
	SortOrder int32
}

type Session struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RefreshTokenHash []byte
	UserAgent        string
	Ip               *netip.Addr
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}
