// Package store owns database access.
//
// Query implementations in *.sql.go and models.go are generated by sqlc from
// db/queries and must not be edited by hand. This file is hand-written and
// holds the connection pool. It is deliberately named pool.go because sqlc
// owns db.go.
package store

import (
	"context"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// enumTypeNames are the user-defined types pgx must learn about on every
// connection, each paired with its array form (the leading underscore is
// Postgres' own naming for an array type).
//
// Without this, pgx knows nothing about these OIDs and fails to encode a
// filter such as brand = ANY($1) with "cannot find encode plan". Decoding
// happens to work without it because sqlc generates a Scan method per enum,
// so the gap only appears on the write side of a query parameter.
var enumTypeNames = []string{
	"brand", "_brand",
	"product_type", "_product_type",
	"lead_source", "_lead_source",
	"lead_status", "_lead_status",
}

// NewPool opens and verifies a Postgres connection pool.
//
// It pings before returning so a bad DATABASE_URL fails at startup rather than
// on the first request that happens to need the database.
func NewPool(ctx context.Context, databaseURL string) (*pgxpool.Pool, error) {
	cfg, err := pgxpool.ParseConfig(databaseURL)
	if err != nil {
		return nil, fmt.Errorf("parse DATABASE_URL: %w", err)
	}

	// Runs once per physical connection, which is cheap at this pool size and
	// is the only point where a connection's type map can be populated.
	cfg.AfterConnect = func(ctx context.Context, conn *pgx.Conn) error {
		types, err := conn.LoadTypes(ctx, enumTypeNames)
		if err != nil {
			return fmt.Errorf("load enum types: %w", err)
		}
		conn.TypeMap().RegisterTypes(types)
		return nil
	}

	// Sized for a small site on a managed Postgres plan with a low connection
	// ceiling. The API is read-heavy and every query is short.
	cfg.MaxConns = 10
	cfg.MinConns = 1
	cfg.MaxConnLifetime = time.Hour
	cfg.MaxConnIdleTime = 5 * time.Minute
	cfg.HealthCheckPeriod = time.Minute

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("create connection pool: %w", err)
	}

	pingCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	if err := pool.Ping(pingCtx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping database: %w", err)
	}

	return pool, nil
}
