// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProductImage = `-- name: AddProductImage :one
INSERT INTO product_images (product_id, object_key, alt, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, object_key, alt, sort_order, created_at
`

type AddProductImageParams struct {
	ProductID pgtype.UUID
	ObjectKey string
	Alt       string
	SortOrder int32
}

func (q *Queries) AddProductImage(ctx context.Context, arg AddProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, addProductImage,
		arg.ProductID,
		arg.ObjectKey,
		arg.Alt,
		arg.SortOrder,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ObjectKey,
		&i.Alt,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    slug, name, brand, type, capacity_pk, btu, starting_price, inverter,
    refrigerant, power_watt, room_size, description, features, featured,
    published, sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, slug, name, brand, type, capacity_pk, btu, starting_price, inverter, refrigerant, power_watt, room_size, description, features, featured, published, sort_order, created_at, updated_at
`

type CreateProductParams struct {
	Slug          string
	Name          string
	Brand         Brand
	Type          ProductType
	CapacityPk    float64
	Btu           int32
	StartingPrice int64
	Inverter      bool
	Refrigerant   string
	PowerWatt     int32
	RoomSize      string
	Description   string
	Features      []string
	Featured      bool
	Published     bool
	SortOrder     int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Slug,
		arg.Name,
		arg.Brand,
		arg.Type,
		arg.CapacityPk,
		arg.Btu,
		arg.StartingPrice,
		arg.Inverter,
		arg.Refrigerant,
		arg.PowerWatt,
		arg.RoomSize,
		arg.Description,
		arg.Features,
		arg.Featured,
		arg.Published,
		arg.SortOrder,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Brand,
		&i.Type,
		&i.CapacityPk,
		&i.Btu,
		&i.StartingPrice,
		&i.Inverter,
		&i.Refrigerant,
		&i.PowerWatt,
		&i.RoomSize,
		&i.Description,
		&i.Features,
		&i.Featured,
		&i.Published,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findProductBySlug = `-- name: FindProductBySlug :one
SELECT id, slug, name, brand, type, capacity_pk, btu, starting_price, inverter, refrigerant, power_watt, room_size, description, features, featured, published, sort_order, created_at, updated_at FROM products WHERE slug = $1
`

// Ignores the published flag. Used by the seeder and by slug-uniqueness checks
// on admin writes, both of which must see unpublished rows.
func (q *Queries) FindProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, findProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Brand,
		&i.Type,
		&i.CapacityPk,
		&i.Btu,
		&i.StartingPrice,
		&i.Inverter,
		&i.Refrigerant,
		&i.PowerWatt,
		&i.RoomSize,
		&i.Description,
		&i.Features,
		&i.Featured,
		&i.Published,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, slug, name, brand, type, capacity_pk, btu, starting_price, inverter, refrigerant, power_watt, room_size, description, features, featured, published, sort_order, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Brand,
		&i.Type,
		&i.CapacityPk,
		&i.Btu,
		&i.StartingPrice,
		&i.Inverter,
		&i.Refrigerant,
		&i.PowerWatt,
		&i.RoomSize,
		&i.Description,
		&i.Features,
		&i.Featured,
		&i.Published,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedProductBySlug = `-- name: GetPublishedProductBySlug :one
SELECT id, slug, name, brand, type, capacity_pk, btu, starting_price, inverter, refrigerant, power_watt, room_size, description, features, featured, published, sort_order, created_at, updated_at FROM products WHERE slug = $1 AND published
`

func (q *Queries) GetPublishedProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getPublishedProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Brand,
		&i.Type,
		&i.CapacityPk,
		&i.Btu,
		&i.StartingPrice,
		&i.Inverter,
		&i.Refrigerant,
		&i.PowerWatt,
		&i.RoomSize,
		&i.Description,
		&i.Features,
		&i.Featured,
		&i.Published,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllProducts = `-- name: ListAllProducts :many

SELECT
    products.id, products.slug, products.name, products.brand, products.type, products.capacity_pk, products.btu, products.starting_price, products.inverter, products.refrigerant, products.power_watt, products.room_size, products.description, products.features, products.featured, products.published, products.sort_order, products.created_at, products.updated_at,
    count(*) OVER () AS total_count
FROM products
ORDER BY sort_order, created_at DESC
LIMIT $2 OFFSET $1
`

type ListAllProductsParams struct {
	ResultOffset int32
	ResultLimit  int32
}

type ListAllProductsRow struct {
	Product    Product
	TotalCount int64
}

// --------------------------------------------------------------------------
// Admin
// --------------------------------------------------------------------------
// Admin listing: includes unpublished rows.
func (q *Queries) ListAllProducts(ctx context.Context, arg ListAllProductsParams) ([]ListAllProductsRow, error) {
	rows, err := q.db.Query(ctx, listAllProducts, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProductsRow{}
	for rows.Next() {
		var i ListAllProductsRow
		if err := rows.Scan(
			&i.Product.ID,
			&i.Product.Slug,
			&i.Product.Name,
			&i.Product.Brand,
			&i.Product.Type,
			&i.Product.CapacityPk,
			&i.Product.Btu,
			&i.Product.StartingPrice,
			&i.Product.Inverter,
			&i.Product.Refrigerant,
			&i.Product.PowerWatt,
			&i.Product.RoomSize,
			&i.Product.Description,
			&i.Product.Features,
			&i.Product.Featured,
			&i.Product.Published,
			&i.Product.SortOrder,
			&i.Product.CreatedAt,
			&i.Product.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedProducts = `-- name: ListFeaturedProducts :many
SELECT id, slug, name, brand, type, capacity_pk, btu, starting_price, inverter, refrigerant, power_watt, room_size, description, features, featured, published, sort_order, created_at, updated_at FROM products
WHERE published AND featured
ORDER BY sort_order, created_at DESC
LIMIT $1
`

func (q *Queries) ListFeaturedProducts(ctx context.Context, limit int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, listFeaturedProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Brand,
			&i.Type,
			&i.CapacityPk,
			&i.Btu,
			&i.StartingPrice,
			&i.Inverter,
			&i.Refrigerant,
			&i.PowerWatt,
			&i.RoomSize,
			&i.Description,
			&i.Features,
			&i.Featured,
			&i.Published,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, object_key, alt, sort_order, created_at FROM product_images
WHERE product_id = ANY ($1::uuid[])
ORDER BY product_id, sort_order
`

// Loaded in one batch for a page of products, then grouped in Go. Keeps the
// listing query free of JSON aggregation.
func (q *Queries) ListProductImages(ctx context.Context, productIds []pgtype.UUID) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImages, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ObjectKey,
			&i.Alt,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedProductSlugs = `-- name: ListPublishedProductSlugs :many
SELECT slug, updated_at FROM products WHERE published ORDER BY slug
`

type ListPublishedProductSlugsRow struct {
	Slug      string
	UpdatedAt pgtype.Timestamptz
}

// Drives sitemap generation and static path generation on the frontend.
func (q *Queries) ListPublishedProductSlugs(ctx context.Context) ([]ListPublishedProductSlugsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedProductSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedProductSlugsRow{}
	for rows.Next() {
		var i ListPublishedProductSlugsRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedProducts = `-- name: ListPublishedProducts :many
SELECT
    products.id, products.slug, products.name, products.brand, products.type, products.capacity_pk, products.btu, products.starting_price, products.inverter, products.refrigerant, products.power_watt, products.room_size, products.description, products.features, products.featured, products.published, products.sort_order, products.created_at, products.updated_at,
    count(*) OVER () AS total_count
FROM products
WHERE published
  AND (cardinality($1::brand[]) = 0 OR brand = ANY ($1::brand[]))
  AND (cardinality($2::product_type[]) = 0 OR type = ANY ($2::product_type[]))
  AND (cardinality($3::numeric[]) = 0 OR capacity_pk = ANY ($3::numeric[]))
ORDER BY sort_order, created_at DESC
LIMIT $5 OFFSET $4
`

type ListPublishedProductsParams struct {
	Brands       []Brand
	Types        []ProductType
	Capacities   []float64
	ResultOffset int32
	ResultLimit  int32
}

type ListPublishedProductsRow struct {
	Product    Product
	TotalCount int64
}

// Catalog listing with optional multi-select facets.
//
// An empty filter array means "no filter on this facet", which lets one query
// serve every combination the catalog UI can produce. The window count returns
// the unpaginated total alongside the page, avoiding a second round trip.
func (q *Queries) ListPublishedProducts(ctx context.Context, arg ListPublishedProductsParams) ([]ListPublishedProductsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedProducts,
		arg.Brands,
		arg.Types,
		arg.Capacities,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedProductsRow{}
	for rows.Next() {
		var i ListPublishedProductsRow
		if err := rows.Scan(
			&i.Product.ID,
			&i.Product.Slug,
			&i.Product.Name,
			&i.Product.Brand,
			&i.Product.Type,
			&i.Product.CapacityPk,
			&i.Product.Btu,
			&i.Product.StartingPrice,
			&i.Product.Inverter,
			&i.Product.Refrigerant,
			&i.Product.PowerWatt,
			&i.Product.RoomSize,
			&i.Product.Description,
			&i.Product.Features,
			&i.Product.Featured,
			&i.Product.Published,
			&i.Product.SortOrder,
			&i.Product.CreatedAt,
			&i.Product.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedProducts = `-- name: ListRelatedProducts :many
SELECT id, slug, name, brand, type, capacity_pk, btu, starting_price, inverter, refrigerant, power_watt, room_size, description, features, featured, published, sort_order, created_at, updated_at FROM products
WHERE published
  AND type = $1
  AND id <> $2
ORDER BY (brand = $3) DESC, sort_order, created_at DESC
LIMIT $4
`

type ListRelatedProductsParams struct {
	Type        ProductType
	ExcludeID   pgtype.UUID
	Brand       Brand
	ResultLimit int32
}

// Products of the same type, excluding the one being viewed. Same brand first,
// so a Daikin page suggests other Daikin units before other brands.
func (q *Queries) ListRelatedProducts(ctx context.Context, arg ListRelatedProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listRelatedProducts,
		arg.Type,
		arg.ExcludeID,
		arg.Brand,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Brand,
			&i.Type,
			&i.CapacityPk,
			&i.Btu,
			&i.StartingPrice,
			&i.Inverter,
			&i.Refrigerant,
			&i.PowerWatt,
			&i.RoomSize,
			&i.Description,
			&i.Features,
			&i.Featured,
			&i.Published,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceProductImages = `-- name: ReplaceProductImages :exec
DELETE FROM product_images WHERE product_id = $1
`

func (q *Queries) ReplaceProductImages(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceProductImages, productID)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
    slug           = $2,
    name           = $3,
    brand          = $4,
    type           = $5,
    capacity_pk    = $6,
    btu            = $7,
    starting_price = $8,
    inverter       = $9,
    refrigerant    = $10,
    power_watt     = $11,
    room_size      = $12,
    description    = $13,
    features       = $14,
    featured       = $15,
    published      = $16,
    sort_order     = $17
WHERE id = $1
RETURNING id, slug, name, brand, type, capacity_pk, btu, starting_price, inverter, refrigerant, power_watt, room_size, description, features, featured, published, sort_order, created_at, updated_at
`

type UpdateProductParams struct {
	ID            pgtype.UUID
	Slug          string
	Name          string
	Brand         Brand
	Type          ProductType
	CapacityPk    float64
	Btu           int32
	StartingPrice int64
	Inverter      bool
	Refrigerant   string
	PowerWatt     int32
	RoomSize      string
	Description   string
	Features      []string
	Featured      bool
	Published     bool
	SortOrder     int32
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Brand,
		arg.Type,
		arg.CapacityPk,
		arg.Btu,
		arg.StartingPrice,
		arg.Inverter,
		arg.Refrigerant,
		arg.PowerWatt,
		arg.RoomSize,
		arg.Description,
		arg.Features,
		arg.Featured,
		arg.Published,
		arg.SortOrder,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Brand,
		&i.Type,
		&i.CapacityPk,
		&i.Btu,
		&i.StartingPrice,
		&i.Inverter,
		&i.Refrigerant,
		&i.PowerWatt,
		&i.RoomSize,
		&i.Description,
		&i.Features,
		&i.Featured,
		&i.Published,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
