// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addServiceRate = `-- name: AddServiceRate :one
INSERT INTO service_rates (service_id, label, unit, price_from, note, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, service_id, label, unit, price_from, note, sort_order
`

type AddServiceRateParams struct {
	ServiceID pgtype.UUID
	Label     string
	Unit      string
	PriceFrom int64
	Note      string
	SortOrder int32
}

func (q *Queries) AddServiceRate(ctx context.Context, arg AddServiceRateParams) (ServiceRate, error) {
	row := q.db.QueryRow(ctx, addServiceRate,
		arg.ServiceID,
		arg.Label,
		arg.Unit,
		arg.PriceFrom,
		arg.Note,
		arg.SortOrder,
	)
	var i ServiceRate
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Label,
		&i.Unit,
		&i.PriceFrom,
		&i.Note,
		&i.SortOrder,
	)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (slug, name, summary, description, bullets, icon, published, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, slug, name, summary, description, bullets, icon, published, sort_order, created_at, updated_at
`

type CreateServiceParams struct {
	Slug        string
	Name        string
	Summary     string
	Description string
	Bullets     []string
	Icon        string
	Published   bool
	SortOrder   int32
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Slug,
		arg.Name,
		arg.Summary,
		arg.Description,
		arg.Bullets,
		arg.Icon,
		arg.Published,
		arg.SortOrder,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.Bullets,
		&i.Icon,
		&i.Published,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :execrows
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteService, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteServiceRates = `-- name: DeleteServiceRates :exec
DELETE FROM service_rates WHERE service_id = $1
`

func (q *Queries) DeleteServiceRates(ctx context.Context, serviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteServiceRates, serviceID)
	return err
}

const findServiceBySlug = `-- name: FindServiceBySlug :one
SELECT id, slug, name, summary, description, bullets, icon, published, sort_order, created_at, updated_at FROM services WHERE slug = $1
`

// Ignores the published flag, for the seeder and slug-uniqueness checks.
func (q *Queries) FindServiceBySlug(ctx context.Context, slug string) (Service, error) {
	row := q.db.QueryRow(ctx, findServiceBySlug, slug)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.Bullets,
		&i.Icon,
		&i.Published,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedServiceBySlug = `-- name: GetPublishedServiceBySlug :one
SELECT id, slug, name, summary, description, bullets, icon, published, sort_order, created_at, updated_at FROM services WHERE slug = $1 AND published
`

func (q *Queries) GetPublishedServiceBySlug(ctx context.Context, slug string) (Service, error) {
	row := q.db.QueryRow(ctx, getPublishedServiceBySlug, slug)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.Bullets,
		&i.Icon,
		&i.Published,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, slug, name, summary, description, bullets, icon, published, sort_order, created_at, updated_at FROM services WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.Bullets,
		&i.Icon,
		&i.Published,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllServices = `-- name: ListAllServices :many

SELECT id, slug, name, summary, description, bullets, icon, published, sort_order, created_at, updated_at FROM services ORDER BY sort_order, name
`

// --------------------------------------------------------------------------
// Admin
// --------------------------------------------------------------------------
func (q *Queries) ListAllServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Summary,
			&i.Description,
			&i.Bullets,
			&i.Icon,
			&i.Published,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedServiceSlugs = `-- name: ListPublishedServiceSlugs :many
SELECT slug, updated_at FROM services WHERE published ORDER BY slug
`

type ListPublishedServiceSlugsRow struct {
	Slug      string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListPublishedServiceSlugs(ctx context.Context) ([]ListPublishedServiceSlugsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedServiceSlugs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedServiceSlugsRow{}
	for rows.Next() {
		var i ListPublishedServiceSlugsRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedServices = `-- name: ListPublishedServices :many
SELECT id, slug, name, summary, description, bullets, icon, published, sort_order, created_at, updated_at FROM services WHERE published ORDER BY sort_order, name
`

func (q *Queries) ListPublishedServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listPublishedServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Summary,
			&i.Description,
			&i.Bullets,
			&i.Icon,
			&i.Published,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceRates = `-- name: ListServiceRates :many
SELECT id, service_id, label, unit, price_from, note, sort_order FROM service_rates
WHERE service_id = ANY ($1::uuid[])
ORDER BY service_id, sort_order
`

// Batched for a set of services, then grouped in Go.
func (q *Queries) ListServiceRates(ctx context.Context, serviceIds []pgtype.UUID) ([]ServiceRate, error) {
	rows, err := q.db.Query(ctx, listServiceRates, serviceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceRate{}
	for rows.Next() {
		var i ServiceRate
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Label,
			&i.Unit,
			&i.PriceFrom,
			&i.Note,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services SET
    slug        = $2,
    name        = $3,
    summary     = $4,
    description = $5,
    bullets     = $6,
    icon        = $7,
    published   = $8,
    sort_order  = $9
WHERE id = $1
RETURNING id, slug, name, summary, description, bullets, icon, published, sort_order, created_at, updated_at
`

type UpdateServiceParams struct {
	ID          pgtype.UUID
	Slug        string
	Name        string
	Summary     string
	Description string
	Bullets     []string
	Icon        string
	Published   bool
	SortOrder   int32
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Summary,
		arg.Description,
		arg.Bullets,
		arg.Icon,
		arg.Published,
		arg.SortOrder,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.Bullets,
		&i.Icon,
		&i.Published,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
