import type { components } from "./schema";

/**
 * Domain types, re-exported from the generated OpenAPI schema.
 *
 * `schema.ts` is generated by `npm run api:types` from the Go API's OpenAPI
 * document and must never be hand-edited. Importing through this file keeps
 * the deep `components["schemas"][...]` paths out of components, and means a
 * backend rename surfaces as a type error in one place.
 */

export type Product = components["schemas"]["ProductDTO"];
export type ProductImage = components["schemas"]["ImageDTO"];
export type Service = components["schemas"]["ServiceDTO"];
export type ServiceRate = components["schemas"]["RateDTO"];
export type Pagination = components["schemas"]["PaginationDTO"];
export type Lead = components["schemas"]["LeadDTO"];
export type AdminUser = components["schemas"]["UserDTO"];
export type SlugEntry = components["schemas"]["SlugEntryDTO"];

export type ProductList = components["schemas"]["ProductListBody"];
export type ServiceList = components["schemas"]["ServiceListBody"];
export type LeadList = components["schemas"]["LeadListBody"];
export type Sitemap = components["schemas"]["SitemapBody"];

export type ProductWrite = components["schemas"]["ProductWrite"];
export type ServiceWrite = components["schemas"]["ServiceWrite"];
export type LeadRequest = components["schemas"]["LeadRequest"];
export type UploadTarget = components["schemas"]["UploadTargetBody"];

/**
 * Literal unions rather than plain strings, carried all the way from the
 * Postgres enums through the Go API's OpenAPI document. A typo in a brand
 * filter is a compile error, not a silently empty result page.
 */
export type Brand = Product["brand"];
export type ProductType = Product["type"];
export type LeadStatus = Lead["status"];
export type LeadSource = Lead["source"];

/** Every brand, in catalog display order. */
export const BRANDS: readonly Brand[] = [
  "gree",
  "daikin",
  "panasonic",
  "midea",
] as const;

/** Every product type, in catalog display order. */
export const PRODUCT_TYPES: readonly ProductType[] = [
  "split-wall",
  "cassette",
  "floor-standing",
  "ceiling-suspended",
  "portable",
] as const;

/** Capacities offered as filter options, in PK. */
export const CAPACITIES: readonly number[] = [
  0.5, 0.75, 1, 1.5, 2, 2.5, 3, 5,
] as const;

/** Narrowing helpers for values arriving from URL search params. */
export function isBrand(value: string): value is Brand {
  return (BRANDS as readonly string[]).includes(value);
}

export function isProductType(value: string): value is ProductType {
  return (PRODUCT_TYPES as readonly string[]).includes(value);
}
